const {inGame}=require('./browser.cjs');
inGame(async(page,errors)=>{
 const results=await page.evaluate(async()=>{
   const E=await import('./engine.js?v=096b'),W=await import('./world.js'),T=await import('./storage.js?v=096b');const results=[];
   const assert=(ok,message)=>{if(!ok)throw Error(message)};
   async function check(name,fn){try{await fn();results.push({name,passed:true})}catch(e){results.push({name,passed:false,error:e.message})}}
   function base(){const s=E.createInitialState(1);s.scene=s.story.sceneId='ch4_end099c';s.chapter=s.story.chapter=4;s.world.environment='indoors';s.world.location='хата баби Галі';s.activeStatuses=[];s.relationships.galina.known=true;s.relationships.galina.values.trust=5;s.clock.totalMinutes=720;return s}
   await check('day and night expose different real actions',()=>{const s=base();const day=W.worldActions(s);s.clock.totalMinutes=1380;const night=W.worldActions(s);assert(day.some(a=>a.id==='carry')&&!day.some(a=>a.id==='listen'),'day actions wrong');assert(!night.some(a=>a.id==='carry')&&night.some(a=>a.id==='listen'),'night actions unchanged');});
   await check('attention changes search duration and hidden find',()=>{const low=base(),high=base();high.stats.attention.level=4;const a=W.performWorldAction(low,'search'),b=W.performWorldAction(high,'search');assert(b.state.clock.totalMinutes<a.state.clock.totalMinutes,'no time benefit');assert(E.itemCount(b.state,'garlic')>E.itemCount(a.state,'garlic'),'hidden item unchanged');});
   await check('strength changes work cost',()=>{const low=base(),high=base();high.stats.strength.level=4;const a=W.performWorldAction(low,'carry'),b=W.performWorldAction(high,'carry');assert(b.state.needs.energy>a.state.needs.energy&&b.state.clock.totalMinutes<a.state.clock.totalMinutes,'strength no effect');});
   await check('charisma and past trust both change help; a poor build still has an alternative',()=>{const low=base(),high=base(),trusted=base();high.stats.charisma.level=4;trusted.relationships.galina.values.trust=8;low.inventory=[];low.money=0;const a=W.performWorldAction(low,'ask-water'),b=W.performWorldAction(high,'ask-water'),c=W.performWorldAction(trusted,'ask-water');assert(a.accepted&&E.itemCount(a.state,'water')===1,'poor build blocked');assert(b.state.clock.totalMinutes<a.state.clock.totalMinutes&&c.state.clock.totalMinutes<a.state.clock.totalMinutes,'help terms unchanged');});
   await check('agility prevents a night-search injury',()=>{const low=base(),high=base();low.clock.totalMinutes=high.clock.totalMinutes=1380;high.stats.agility.level=4;const a=W.performWorldAction(low,'search'),b=W.performWorldAction(high,'search');assert(b.state.health>a.state.health,'agility no effect');});
   await check('pofigism prevents fear from night exploration',()=>{const low=base(),high=base();low.clock.totalMinutes=high.clock.totalMinutes=1380;high.stats.pofigism.level=4;assert(W.performWorldAction(low,'listen').state.activeStatuses.includes('scared'),'low stat has no consequence');assert(!W.performWorldAction(high,'listen').state.activeStatuses.includes('scared'),'high stat has no benefit');});
   await check('ahui reduces the cost of checking fog without ending the story',()=>{const low=base(),high=base();for(const s of [low,high]){s.scene=s.story.sceneId='ch7_shed_truth100';s.chapter=s.story.chapter=7;s.flags.darinaRevealed100=true;s.world.location='білий туман'}high.stats.ahui.level=4;const a=W.performWorldAction(low,'fog-markers'),b=W.performWorldAction(high,'fog-markers');assert(b.state.clock.totalMinutes<a.state.clock.totalMinutes,'ahui has no effect');assert(b.state.scene==='ch7_shed_truth100'&&b.state.world.location==='білий туман','new story ending invented');});
   await check('once-only stock and XP survive reload',async()=>{let s=W.performWorldAction(base(),'search').state;await T.saveRun(s);s=E.normalizeState(await T.loadRun(1));const xp=s.heroProgression.xp,bag=JSON.stringify(s.inventory),r=W.performWorldAction(s,'search');assert(!r.accepted&&r.state.heroProgression.xp===xp&&JSON.stringify(r.state.inventory)===bag,'repeated farming');});
   await check('time advances only on actions; browsing costs nothing',()=>{const s=base(),before=JSON.stringify(s);W.worldActions(s);W.worldActions(s);assert(JSON.stringify(s)===before,'inspection mutated state');const r=W.performWorldAction(s,'search');assert(r.state.clock.totalMinutes>s.clock.totalMinutes,'action did not advance time');});
   await check('full-bag find remains available after making room',()=>{const s=base();s.inventory=Array.from({length:16},()=>({id:'knife',qty:1}));const r=W.performWorldAction(s,'search');assert(r.state.pendingLoot.length===1,'find lost');E.removeItem(r.state,'knife',1);const collected=W.performWorldAction(r.state,'collect-0');assert(collected.accepted&&E.itemCount(collected.state,'onion')===1&&collected.state.pendingLoot.length===0,'pending find cannot be recovered');});
   await check('water, food and fatigue produce actual statuses and recover',()=>{const s=base();s.needs={satiety:10,water:10,energy:10};const n=E.executeAction(s,{}).state;assert(['hungry','thirsty','tired'].every(id=>n.activeStatuses.includes(id)),'physiology missing');const r=E.executeAction(n,{effects:[{type:'need',key:'satiety',value:90},{type:'need',key:'water',value:90},{type:'need',key:'energy',value:90}]}).state;assert(!['hungry','thirsty','tired'].some(id=>r.activeStatuses.includes(id)),'physiology did not recover');});
   await check('washing removes skunk and dirty-clothing status',()=>{const s=base();s.activeStatuses=['skunk','pigeonHumiliated'];s.flags.modernJacketPooped=true;const r=W.performWorldAction(s,'wash');assert(r.accepted&&!r.state.activeStatuses.includes('skunk')&&!r.state.activeStatuses.includes('pigeonHumiliated')&&!r.state.flags.modernJacketPooped,'wash is cosmetic');});
   await check('danger blocks long rest and scavenging without hiding combat alternatives',()=>{const s=base();s.scene=s.story.sceneId='ch3_creature';s.chapter=s.story.chapter=3;s.world.location='за сараєм';const actions=W.worldActions(s);assert(actions.some(a=>a.id==='read-danger')&&!actions.some(a=>a.id==='rest'||a.id==='search'),'unsafe activities offered');});
   await check('chapter 6 uses separate supplies and clothing, chapter 7 restores Stepan',async()=>{let s=base();s.health=37;E.addItem(s,'water',3);s.scene=s.story.sceneId='ch6_yard099d';s.chapter=s.story.chapter=6;const bird=E.normalizeState(W.syncActor(s));assert(bird.activeActor==='evpapiy'&&E.itemCount(bird,'water')===0&&bird.ownedClothes.length===0&&Object.values(bird.equipment).every(v=>v===null),'human inventory or equipment teleported');await T.saveRun(bird);let loaded=E.normalizeState(await T.loadRun(1));E.addItem(loaded,'salo',1);loaded.scene=loaded.story.sceneId='ch7_intro100';const stepan=E.normalizeState(W.syncActor(loaded));assert(stepan.health===37&&E.itemCount(stepan,'water')===3&&E.itemCount(stepan,'salo')===1,'Stepan profile changed by bird actions');});
   return results;
 });
 try{
 await page.evaluate(async()=>{const E=await import('./engine.js?v=096b'),T=await import('./storage.js?v=096b');const s=E.createInitialState(3);s.flags.initialStatusPopupShown=true;await T.saveRun(s)});
 await page.locator('#continueBtn').click();await page.locator('.run-card').filter({hasText:'Проходження 3'}).click();await page.locator('#menuBtn').click();await page.locator('[data-tab="place"]').evaluate(e=>e.click());await page.locator('[data-world-action="pockets"]').click();
 const live=await page.evaluate(async()=>{const M=await import('./main.js?v=095');return M.readGameState()});if(!live.journal.some(e=>e.id==='pockets')||!live.inventory.some(i=>i.id==='aspirin'))throw Error('UI world action did not persist');
 await page.locator('[data-tab="journal"]').evaluate(e=>e.click());if(!await page.locator('#menuContent').innerText().then(t=>t.includes('Перевірити власні кишені')))throw Error('Journal missing UI action');results.push({name:'Place action through actual menu updates live state, save and journal',passed:true});
 }catch(e){results.push({name:'Place action through actual menu updates live state, save and journal',passed:false,error:e.message})}
 console.log(JSON.stringify({suite:'world',results,errors},null,2));if(results.some(r=>!r.passed)||errors.length)process.exitCode=1;
}).catch(e=>{console.error(e);process.exitCode=1});
